spring:
    application:
        name: springdataredis_demo
    #Redis???? 1234
    redis:
        host: 192.168.20.147
        port: 6379
        password: 123456
        database: 0 #????0????
        jedis:
            #Redis?????
            pool:
                max-active: 8 #?????
                max-wait: 1ms #???????????
                max-idle: 4 #???????????
                min-idle: 0 #???????????